#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` file.asm"
    exit 1
fi

OPTS="-m68000 -no-opt -Fbin -rangewarnings"
vasmm68k_mot $OPTS -o "$1.bin" "$1"  2>&1 | sed -e '/displacement out of range/{N;N;d}'
